### PR TITLE
Add the Test Resource Folder with jfr files

### PR DESCRIPTION
**Pull request by AfiMaameDufie**
- [x] Added the Test Resource Folder with jfr files

NB: Took out certain test files  because they conflict

### CODE REVIEW

**Comment by rorygraves** [comment]
This has a whole bunch of  unrelated files in (.idea folder - please remove)

**Comment by AfiMaameDufie** [comment]
> This has a whole bunch of unrelated files in (.idea folder - please remove)

Okay. On it.

**Comment by AfiMaameDufie** [comment]
@rorygraves 
That folder totally skipped me. I used it initially to test certain parts of the code.
I have deleted it now.

**Comment by rorygraves** [comment]
> @rorygraves
> That folder totally skipped me. I used it initially to test certain parts of the code.
> I have deleted it now
You need to squahs the commits and also remove the random files you have inherited from elsewhere e.g. ClassInfo should not be in your Pr.

**Pull request merged**
